In [17]:
import numpy as np

def ReLU(x):
    return np.maximum(x, 0, x) #ReLU in place, instead of creating a new var this works on the original matrix

def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-1.0*x)) #sigmoid function

def feed_forward(features,w1,b1,w2,b2,w3,b3,method=2):
    HL1 = np.matmul(w1,features)
    HL1_with_bias = np.add(HL1,b1)
    HL1_with_bias_and_activation = np.maximum(HL1_with_bias,np.zeros((4,1)))

    HL2 = np.matmul(w2,HL1_with_bias_and_activation)
    HL2_with_bias = np.add(HL2,b2)
    HL2_with_bias_and_activation = np.maximum(HL2_with_bias,np.zeros((3,1)))
    
    targets_predicted = np.matmul(w3,HL2_with_bias_and_activation)
    targets_predicted = np.add(targets_predicted,b3)
    
    if method == 1:
        # Use ReLU for the output activation
        targets_predicted = ReLU(targets_predicted)
    else:
         # Use sigmoid for the output activation
        targets_predicted = sigmoid(targets_predicted)
    return targets_predicted
    
print('Starting ...')

## Set up training data
## Each row is a case
## Columns 0-4 are features
## Columns 5 & 6 are targets

features_and_targets = np.array( 
                                   [ [0, 0, 0, 0, 0, 0, 1],
                                     [0, 0, 0, 0, 1, 0, 1],
                                     [0, 0, 0, 1, 1, 0, 1],
                                     [0, 0, 1, 1, 1, 0, 1],
                                     [0, 1, 1, 1, 1, 0, 1],
                                     [1, 1, 1, 1, 0, 0, 1],
                                     [1, 1, 1, 0, 0, 0, 1],
                                     [1, 1, 0, 0, 0, 0, 1],
                                     [1, 0, 0, 0, 0, 0, 1],
                                     [1, 0, 0, 1, 0, 0, 1],
                                     [1, 0, 1, 1, 0, 0, 1],
                                     [1, 1, 0, 1, 0, 0, 1],
                                     [0, 1, 0, 1, 1, 0, 1],
                                     [0, 0, 1, 0, 1, 0, 1],
                                     [1, 0, 1, 1, 1, 1, 0],
                                     [1, 1, 0, 1, 1, 1, 0],
                                     [1, 0, 1, 0, 1, 1, 0],
                                     [1, 0, 0, 0, 1, 1, 0],
                                     [1, 1, 0, 0, 1, 1, 0],
                                     [1, 1, 1, 0, 1, 1, 0],
                                     [1, 1, 1, 1, 1, 1, 0],
                                     [1, 0, 0, 1, 1, 1, 0]  ]
                           , dtype=float)

# shuffle our cases
np.random.shuffle(features_and_targets)

features = np.transpose(features_and_targets[:,0:5])
targets_observed = np.transpose(features_and_targets[:,5:7])

number_of_features,number_of_cases = features.shape
print("Number of Features: %s" % number_of_features)
print("Number of Cases: %s" % number_of_cases)
    
#Set initial weights and biases
np.random.seed(1)  
weights_1 = np.random.randn(4,5)
biases_1 = np.random.randn(4,number_of_cases)

weights_2 = np.random.randn(3,4)
biases_2 = np.random.randn(3,number_of_cases)

weights_3 = np.random.randn(2,3)
biases_3 = np.random.randn(2,number_of_cases)
# You need to set your initil weights and biases here

def __main__():
    user_chose = False
    user_method = 2
    while not user_chose:
        inp = input("Enter 1 for ReLU or 2 for Sigmoid: ")
        if inp == "1":
            print("Using ReLU")
            user_method = 1
            user_chose = True
        elif inp == "2":
            print("Using Sigmoid")
            user_method = 2
            user_chose = True
        else:
            print("You must choose between 1 (ReLU) or 2 (Sigmoid)")
            
    Targets_Predicted = feed_forward(features,weights_1,biases_1,
                                          weights_2,biases_2,
                                          weights_3,biases_3,
                                          method=user_method)

    print('Features : %s' % features)
    print('Targets : %s' % targets_observed)
    print('Targets predicted : %s' % Targets_Predicted)
    
#Lets run it the first time, this time we will choose ReLU
__main__()
    
    

Starting ...
Number of Features: 5
Number of Cases: 22


Enter 1 for ReLU or 2 for Sigmoid:  1


Using ReLU
Features :  [[0. 0. 0. 1. 1. 0. 0. 0. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 1. 1. 1. 0. 1. 1. 0. 1. 1. 0. 0.]
 [1. 1. 0. 1. 1. 0. 0. 0. 1. 0. 0. 0. 1. 1. 0. 1. 0. 0. 1. 0. 0. 1.]
 [0. 1. 1. 0. 1. 0. 1. 0. 0. 0. 0. 1. 1. 0. 1. 1. 0. 0. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 0. 1. 1. 1. 0. 0. 1. 1. 0. 1. 1. 1. 1. 0. 0. 0. 0.]]
 Targets :  [[0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 0. 1. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 1. 1. 1. 0. 1. 1. 0. 1. 1. 0. 0. 0. 0. 1. 1. 1. 1.]]
 Targets predicted :  [[2.7716405  1.15819049 1.49965915 0.         3.20744717 1.18733497
  1.77470879 1.47002898 1.53197985 0.86477786 0.58944954 2.56453162
  0.         0.         0.         0.         0.         3.23988349
  0.18758916 0.         1.72204781 0.        ]
 [1.0216593  1.10302102 0.51415203 3.01899796 7.38465859 0.02944774
  1.49174036 1.55809795 5.77003396 0.1055537  2.36390272 5.38786273
  0.         0.         2.11897215 0.2814142  1.13721652 3.51321062
  1

In [19]:
#Lets run it again, this time we will choose sigmoid
__main__()

Enter 1 for ReLU or 2 for Sigmoid:  2


Using Sigmoid
Features :  [[0. 0. 0. 1. 1. 0. 0. 0. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 1. 1. 1. 0. 1. 1. 0. 1. 1. 0. 0.]
 [1. 1. 0. 1. 1. 0. 0. 0. 1. 0. 0. 0. 1. 1. 0. 1. 0. 0. 1. 0. 0. 1.]
 [0. 1. 1. 0. 1. 0. 1. 0. 0. 0. 0. 1. 1. 0. 1. 1. 0. 0. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 0. 1. 1. 1. 0. 0. 1. 1. 0. 1. 1. 1. 1. 0. 0. 0. 0.]]
 Targets :  [[0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 0. 1. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 1. 1. 1. 0. 1. 1. 0. 1. 1. 0. 0. 0. 0. 1. 1. 1. 1.]]
 Targets predicted :  [[0.94112395 0.76100376 0.81752363 0.38097733 0.96111357 0.76626409
  0.85504228 0.81306179 0.82229581 0.70365792 0.64323884 0.92854372
  0.20883672 0.1898681  0.40750777 0.32694636 0.28221063 0.96230788
  0.54676025 0.20707037 0.84839242 0.38175414]
 [0.73529568 0.75082573 0.6257793  0.95342505 0.99937968 0.5073614
  0.81633935 0.82608025 0.99689005 0.52636395 0.91403296 0.99544907
  0.36684539 0.44051083 0.89273354 0.5698929  0.75716822 0.97106132
 